# coding: utf-8

"""
    Python APIs for oaCORE

    Python APIs for oaCORE

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import os
import sys
import unittest
import argparse

import pyoacore
from pyoacore.rest import ApiException
from pyoacore.apis.articles_api import ArticlesApi
from pyoacore.configuration import Configuration


class TestArticlesApi(unittest.TestCase):
    """ ArticlesApi unit test stubs """

    @classmethod
    def setUpClass(cls):
        cls.api = pyoacore.apis.articles_api.ArticlesApi()

    @classmethod
    def tearDown(cls):
        pass

    def test_articles_get_core_id_get(self):
        """
        Test case for articles_get_core_id_get

        Get articles by ID

        """
        results = self.api.articles_get_core_id_get(43)
        print(results)
        assert results['id'] == '43'
        pass

    def test_articles_get_core_id_post(self):
        """
        Test case for articles_get_core_id_get

        Get articles by ID

        """
        results = self.api.articles_get_core_id_post(43)
        print(results)
        assert results['id'] == '43'
        pass

    def test_articles_search_api_call(self):
        """
        Test case for articles_search_api_call

        Search articles

        """
        results = self.api.articles_search_api_call(
                {"query": "repositories.id:(88)", "page": 1, "pageSize": 10, "fulltext": True})
        print(results)
        assert len(results) > 0
        pass


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--key', default='enter_your_key')
    args = parser.parse_args()
    sys.argv[1:] = args.unittest_args
    args = parser.parse_args()
    config = Configuration()
    config.api_key = {"api_key": "asddsds"}
    unittest.main()
