# coding: utf-8

"""
    Python APIs for oaCORE

    Python APIs for oaCORE

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import pyoacore
from pyoacore.rest import ApiException
from pyoacore.models.article import Article


class TestArticle(unittest.TestCase):
    """ Article unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArticle(self):
        """
        Test Article
        """
        model = pyoacore.models.article.Article()


if __name__ == '__main__':
    unittest.main()
