language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python -m unittest discover; fi