# coding: utf-8

"""
    Python APIs for oaCORE

    Python APIs for oaCORE

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.article import Article

# import apis into sdk package
from .apis.articles_api import ArticlesApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration( )
