# coding: utf-8

"""
    Python APIs for oaCORE

    Python APIs for oaCORE

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .article import Article
